name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
        exclude:
          - os: windows-latest
            python-version: '3.8'
          - os: windows-latest
            python-version: '3.9'
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      
    - name: Install maturin
      run: |
        pip install maturin
        
    - name: Build
      run: |
        maturin build --release --features macos
        
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        path: target/wheels/*.whl
        name: wheels
        
  publish:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: wheels
        path: dist
        
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }} 